[Scans]
UAssetLoader_LoadTargetAsset=48 89 5C 24 ?? 48 89 74 24 ?? 48 89 7C 24 ?? 41 56 48 83 EC 50 48 8B 02
;UAssetLoader_LoadTargetAsset_RESULT
UAssetLoader_LoadQueuedAssets=48 89 E0 41 56 48 81 EC 90 00 00 00
;UAssetLoader_LoadQueuedAssets_RESULT
UAssetLoader_CreateStreamHandle=48 89 E0 41 56 48 81 EC 90 00 00 00
;UAssetLoader_CreateStreamHandle_RESULT